/** Save-transfer wire format. Lets a player move terminal-day records
 *  between devices via a base64-encoded JSON envelope copied through any
 *  text channel (Messages, Notes, email).
 *
 *  Scope: terminal days only (won or lost). In-progress sessions don't
 *  cross devices — they're cheap to redo and the merge semantics aren't
 *  worth the code.
 *
 *  The wire `Guess` deliberately omits `ids`, which would reveal which
 *  specific tracks were chosen in incorrect guesses. The emoji grid only
 *  needs `themes` and `correct`. */
import type { Guess } from './types';

/** Bump when the wire shape changes in a way an old importer would
 *  misinterpret. Adding optional fields doesn't require a bump; renaming,
 *  removing, or repurposing fields does. The per-day localStorage `__v` is
 *  a separate concern and lives in storage.ts. */
export const FORMAT_VERSION = 1;
const APP_TAG = 'audio-connections';

export interface TransferGuess {
  themes: number[];
  correct: boolean;
}

export interface PerDayRecord {
  day: number;
  outcome: 'won' | 'lost';
  /** Omitted for editor-synthesized records. EndPanel renders a summary
   *  card when absent and the full emoji grid when present. */
  guessHistory?: TransferGuess[];
}

export interface TransferEnvelope {
  formatVersion: number;
  exportedAt: string;
  app: typeof APP_TAG;
  days: PerDayRecord[];
}

export function encodeBackup(days: PerDayRecord[], now: Date = new Date()): string {
  const envelope: TransferEnvelope = {
    formatVersion: FORMAT_VERSION,
    exportedAt: now.toISOString(),
    app: APP_TAG,
    days,
  };
  return btoa(JSON.stringify(envelope));
}

export type DecodeResult =
  | { ok: true; envelope: TransferEnvelope }
  | { ok: false; error: string };

export function decodeBackup(b64: string): DecodeResult {
  const trimmed = b64.trim();
  if (!trimmed) return { ok: false, error: 'Empty input.' };

  let json: string;
  try {
    json = atob(trimmed);
  } catch {
    return { ok: false, error: "Doesn't look like a backup string." };
  }

  let parsed: unknown;
  try {
    parsed = JSON.parse(json);
  } catch {
    return { ok: false, error: 'Backup is corrupted (not valid JSON).' };
  }

  if (!isObject(parsed)) return { ok: false, error: 'Backup is not an object.' };
  if (parsed.app !== APP_TAG) {
    return { ok: false, error: 'This backup was generated by a different app.' };
  }
  if (typeof parsed.formatVersion !== 'number') {
    return { ok: false, error: 'Backup is missing a format version.' };
  }
  if (parsed.formatVersion > FORMAT_VERSION) {
    return {
      ok: false,
      error: 'Backup was generated by a newer build of Audio Connections. Update this device to import it.',
    };
  }
  if (!Array.isArray(parsed.days)) {
    return { ok: false, error: 'Backup is missing the days list.' };
  }

  const days: PerDayRecord[] = [];
  for (let i = 0; i < parsed.days.length; i++) {
    const record = validateRecord(parsed.days[i]);
    if (!record) return { ok: false, error: `Day record #${i + 1} is malformed.` };
    days.push(record);
  }

  return {
    ok: true,
    envelope: {
      formatVersion: parsed.formatVersion,
      exportedAt: typeof parsed.exportedAt === 'string' ? parsed.exportedAt : '',
      app: APP_TAG,
      days,
    },
  };
}

function validateRecord(raw: unknown): PerDayRecord | null {
  if (!isObject(raw)) return null;
  if (typeof raw.day !== 'number' || !Number.isFinite(raw.day)) return null;
  if (raw.outcome !== 'won' && raw.outcome !== 'lost') return null;

  if (raw.guessHistory === undefined) {
    return { day: raw.day, outcome: raw.outcome };
  }
  if (!Array.isArray(raw.guessHistory)) return null;

  const guessHistory: TransferGuess[] = [];
  for (const g of raw.guessHistory) {
    if (!isObject(g)) return null;
    if (typeof g.correct !== 'boolean') return null;
    if (!Array.isArray(g.themes)) return null;
    const themes: number[] = [];
    for (const t of g.themes) {
      if (typeof t !== 'number' || !Number.isFinite(t)) return null;
      themes.push(t);
    }
    guessHistory.push({ themes, correct: g.correct });
  }

  return { day: raw.day, outcome: raw.outcome, guessHistory };
}

function isObject(v: unknown): v is Record<string, unknown> {
  return typeof v === 'object' && v !== null;
}

/** Project a runtime Guess (which carries selected track ids for dedup)
 *  to the wire shape, stripping ids so the transfer never reveals which
 *  specific incorrect tracks the player picked. */
export function toTransferGuess(g: Guess): TransferGuess {
  return { themes: g.themes, correct: g.correct };
}
